import { ArchGraph, NodeType } from './types'

export const mockWhatsAppGraph: ArchGraph = {
  system: 'WhatsApp',
  description:
    'Real-time messaging platform serving 2B+ users with end-to-end encryption, media sharing, and presence indicators at global scale.',
  nodes: [
    {
      id: 'mobile-client',
      type: NodeType.CLIENT,
      label: 'Mobile Client',
      description: 'iOS and Android clients with WebSocket connections',
      tech: 'React Native',
      scale: '2B users',
      capacity: 999999,
      position: { x: 520, y: 80 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'websocket-lb',
      type: NodeType.LOAD_BALANCER,
      label: 'WebSocket LB',
      description: 'Layer 7 load balancer for persistent WebSocket connections',
      tech: 'HAProxy',
      scale: '50K conn/s',
      capacity: 50000,
      position: { x: 300, y: 220 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'media-lb',
      type: NodeType.LOAD_BALANCER,
      label: 'Media LB',
      description: 'Load balancer for media upload/download traffic',
      tech: 'NGINX',
      scale: '30K req/s',
      capacity: 30000,
      position: { x: 700, y: 220 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'chat-service',
      type: NodeType.SERVICE,
      label: 'Chat Service',
      description: 'Handles message routing, delivery, and E2E encryption',
      tech: 'Erlang/OTP',
      scale: '10K msg/s',
      capacity: 10000,
      position: { x: 180, y: 380 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'presence-service',
      type: NodeType.SERVICE,
      label: 'Presence Service',
      description: 'Tracks online/offline status and last seen timestamps',
      tech: 'Go',
      scale: '8K updates/s',
      capacity: 8000,
      position: { x: 380, y: 380 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'media-service',
      type: NodeType.SERVICE,
      label: 'Media Service',
      description: 'Processes image, video, and document uploads',
      tech: 'Java',
      scale: '5K uploads/s',
      capacity: 5000,
      position: { x: 620, y: 380 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'notification-service',
      type: NodeType.SERVICE,
      label: 'Notification Service',
      description: 'Push notifications via APNs and FCM',
      tech: 'Python',
      scale: '12K push/s',
      capacity: 12000,
      position: { x: 820, y: 380 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'cassandra',
      type: NodeType.DATABASE,
      label: 'Cassandra',
      description: 'Distributed NoSQL for message history and metadata',
      tech: 'Apache Cassandra',
      scale: 'Petabytes',
      capacity: 20000,
      position: { x: 180, y: 540 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'redis',
      type: NodeType.CACHE,
      label: 'Redis',
      description: 'In-memory cache for sessions, presence, and hot data',
      tech: 'Redis Cluster',
      scale: '50K ops/s',
      capacity: 50000,
      position: { x: 380, y: 540 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 's3',
      type: NodeType.DATABASE,
      label: 'S3',
      description: 'Object storage for media files and backups',
      tech: 'Amazon S3',
      scale: 'Exabytes',
      capacity: 99999,
      position: { x: 620, y: 540 },
      status: 'healthy',
      currentLoad: 0,
    },
    {
      id: 'kafka',
      type: NodeType.QUEUE,
      label: 'Kafka',
      description: 'Event streaming for async message delivery and fan-out',
      tech: 'Apache Kafka',
      scale: '40K events/s',
      capacity: 40000,
      position: { x: 820, y: 540 },
      status: 'healthy',
      currentLoad: 0,
    },
  ],
  edges: [
  {
      id: 'e1',
      source: 'mobile-client',
      target: 'websocket-lb',
      label: 'WebSocket',
      animated: true,
      throughput: 45000,
    },
    {
      id: 'e2',
      source: 'mobile-client',
      target: 'media-lb',
      label: 'HTTPS',
      animated: true,
      throughput: 25000,
    },
    {
      id: 'e3',
      source: 'websocket-lb',
      target: 'chat-service',
      animated: true,
      throughput: 28000,
    },
    {
      id: 'e4',
      source: 'websocket-lb',
      target: 'presence-service',
      animated: true,
      throughput: 17000,
    },
    {
      id: 'e5',
      source: 'media-lb',
      target: 'media-service',
      animated: true,
      throughput: 22000,
    },
    {
      id: 'e6',
      source: 'chat-service',
      target: 'cassandra',
      label: 'write',
      animated: true,
      throughput: 15000,
    },
    {
      id: 'e7',
      source: 'chat-service',
      target: 'redis',
      label: 'cache',
      animated: true,
      throughput: 35000,
    },
    {
      id: 'e8',
      source: 'chat-service',
      target: 'kafka',
      label: 'publish',
      animated: true,
      throughput: 12000,
    },
    {
      id: 'e9',
      source: 'presence-service',
      target: 'redis',
      animated: true,
      throughput: 20000,
    },
    {
      id: 'e10',
      source: 'media-service',
      target: 's3',
      animated: true,
      throughput: 18000,
    },
    {
      id: 'e11',
      source: 'notification-service',
      target: 'kafka',
      label: 'consume',
      animated: true,
      throughput: 10000,
    },
  ],
  tradeoffs: [
    'Cassandra chosen over PostgreSQL for write-heavy message storage at 2B user scale, accepting eventual consistency for cross-region replication.',
    'WebSocket connections pinned to specific servers — requires sticky sessions and complicates horizontal scaling of connection layer.',
    'E2E encryption means server cannot inspect message content — limits spam detection and content moderation to metadata-only approaches.',
    'Kafka fan-out decouples message delivery from chat service but adds latency for offline message delivery (typically 100-500ms).',
    'Redis as single point for presence data — cluster mode mitigates but hot keys for popular group chats remain a bottleneck.',
  ],
  scale_numbers: {
    users: '2B',
    messages_per_day: '100B',
    p99_latency: '50ms',
    storage: 'Petabytes',
    uptime: '99.99%',
  },
  scores: {
    latency: 7,
    scalability: 9,
    consistency: 6,
    cost: 5,
    complexity: 8,
  },
}
